# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WUsLkBS5u3/ds2CjBOIBZX8=,iv:xRjfdiTGW/A9JFwT6QiojCvOtXlJBtqO+vfXe5uRgNQ=,tag:zqXi4BNu9YFhvKJx5llDmw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FFj9oEES0evuztGpR1bOlszYsOju3wE=,iv:sYHrf1THgyS29lCpXJOHOol63CIiG+C+oLIHB3Zj3AQ=,tag:s52etbMraWr8vkKYQB5Qsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-17T18:34:17Z"
    mac: ENC[AES256_GCM,data:R55AMl+LwiRCLdhJE2My/NtuhnV/f/bI+3bZOpdNpeHzd5zcEheZa4tBGifv8tknz5pjJjOP6tzeGMiA0kVMH4aPgIEf5M+q5i3O3hfzXEmkTFtY5+YWq2VnY+LzkrRMYICdmfN5PpYZ+fzwdcVi7jmdDFUYpj8qvifTRAw8pxg=,iv:SRtWFmPs3S1VVJtVa81Fi/Cfz+Sj89fELvaz3sMsU5A=,tag:rQQUb4HTDzDrguNY5iRj+g==,type:str]
    pgp:
        - created_at: "2021-08-17T18:34:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9zFjletU/C6AQ//U3lMOfYKhL7RHIbCAayJz1I0Y3Gr4kgjAypuuAtb3EWi
            3+pBfZ1DNh+rJyhdm/l1Nft8OmzyYnjNxDoPyVPFqdqw0ZgqkbmGzwyLxkuYDAkS
            1YVKdouS5RB/Hn+ZfY8CyTjVVr78jtMU+D0W5ltOFAq4W3fDZ5lReXwm0n5//GIt
            +uclOyQ0S+gh+zyWRfM1p+XQCgitgHlz4w0lE/gayXZIkpmsQkbCZmDnlrl+86aW
            181jk6a6WxPLpe76DSkb7xFTrnYAEhJDV8LnZmkyrYCmbPhm9cGIOeEklTvuTS3O
            jVmN9XgEDGiOTnxp5ChjpmTigikQd+WXF3c1+yqOIncTHDZr/j9WJxcWo9nGpKA8
            DHhlV820x0txy9GYE/ipQ9Epse+ze9nI6a8u25aKSFCGmJ9viFPUw2TctnJV8RRJ
            IjkxcdyujjuksM1pMoCgq6kfFqxbo6zHQJmRMCAtzL8pkQE7ky3UIRZwhI1VlUEz
            eVf2vYlRCw43wTv0NDtt1Ihc+MWIYwArTQt9tR06Mjvd+YqMxATYwD94EVepxql/
            lsndhwg6ITTlpxtW72P0CqhObm4TyBatuRvIw1rkyvmapMwpBSLwIC9UZx4uZyj+
            HBT98eQqc66eOwAaJ0ZvVZoXu2SktYCfKU3chADFLOSKwFZg0VN3H4thqn41zmTS
            XgF2KXXDLBD2UI2Kc6LiGqSXXAs2MWJqEMfRPvNNd844b5D1Pf0Pcc3u7yJsciVC
            NVDkuutu/LgaAknoAG7bx7wqmO4YN36iG2ZYDQHPqWNc/qxbG4nuu4BvtawyH5c=
            =63jG
            -----END PGP MESSAGE-----
          fp: 278C46304C1DEEF4C1A2263F7D68B8BD56F1FB2F
        - created_at: "2021-08-17T18:34:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1potYVbjnpWAQ/6Ahd2pt5EtItS4+w8y6rD5zT8I2cjj7qP/T6LW+lw5XZK
            8SQtb2NJD9LO4i+/+ivh6W6sHtohM0SUse9itJ5XWxW14W1SOMmmW8LHBa0yka/s
            +ZyCLVxnu3eZHzfLWp2euR8ls1axheGLMxhMfQ7/5wzOGIsv/HvfNkrYOhbrBvCL
            6Ws4xT/cDZQTQWK6x1VMTyZ7DEs224Gmq76lqp+N1DKyHaJHvvz0oTMLTW44KM7t
            /RPIbJnSessxskuOo6j0F3rzamwPG3lrk9rZhUROTzQLj/3t+0BiAQQyZ5vb/jKk
            dYC2qgI2bDCPBiebHpIkBsptAulKH37oAksKmzgxj7kDuIgi5ABpY0x4DCAdyxRC
            5DRzjTOy6sWYyhxz9O6Khn3M5Wt4MKM5KSoe8jEVgNgDp4/Htp8FxEZptZqc/+MD
            +jb3Kj+N01TpmbmgStGM6kN0js1AhyXjlXNfJwVgdQVcUn9oJqW7VFtJXgJqdr/g
            JJGV7557BTbRGB/iXsXMYLFJKhat0MnEqiewjZZrD8pzCvCX5/UeG7EcU0GX6rC+
            tjHZwReF8sBFGKdB6Df5rq7297IfZegR/s2wftWMumF4au+CCsZP2Lm0Z6zu60/N
            069zGyu6tKmOj4Re+j0oi0FikGancG4OSICH7KD0zoLFLO4PwTaHaZye5re0jkbS
            XgHy1M9MWXCQcRJx5zwRxQotJAxPe4/w25zQ95Zc9971r9EIsy0Vb/QRVxCNyfcH
            83yzrCrNYe24KFF0CdhJWtD+h5Q+0GM4XeDauTONdKbnvDT2STaVkxvpIqlJFdc=
            =o87d
            -----END PGP MESSAGE-----
          fp: 71D3D0A4DC6258EFFAD212EAC976676516F69FA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
